### ISSUE TITLE
필수로 만들어 져야 하는 로직

### ISSUE THREAD

**Issue by UnitySio** [Github-AppData/graduate_task#6]
오브젝트 풀: 런타임에서 오브젝트를 생성하고 삭제하는 것 자체가 비용이 비싸기 때문에 필수로 개발되어야 함

오디오 매니저: 배경음악은 하나만 재생하기 때문에 문제 없지만 효과음 같은 경우 동시에 재생해야 하는 경우가 생기기 때문에 채널 단위로 관리를 하여 재생하도록 개발되어야 함

-마지막으로 도움 주고 감-
-언젠가는 성장하길 바람-
-확인하면 이 이슈는 Close 하셈-

**Comment by Github-AppData** [comment]
Thanks
